default: &default
  adapter: postgresql
  encoding: utf8
  username: postgres
  password: 1
  host: localhost

development:
  <<: *default
  database: development_test_task_api

test:
  <<: *default
  database: test_test_task_api

