default: &default
  adapter: postgresql
  encoding: utf8
  username: username
  password: password
  host: localhost

development:
  <<: *default
  database: development_test_task_api

test:
  <<: *default
  database: test_test_task_api

production:
  <<: *default
  database: production_test_task_api
